from .index import *
from .auth import *
from .community import *
from .tasks import *
from .timetable import *
from .notes import *
from .market import *
from .attendance import *
from .dashboard import *
from .settings import *
