# Generated by Django 2.2.6 on 2019-10-30 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191030_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sub', models.CharField(max_length=255)),
                ('topic_date', models.DateTimeField(auto_now_add=True)),
                ('topic_posts', models.IntegerField(default=0)),
                ('topic_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_upvote', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('post_downvote', models.IntegerField(default=0, verbose_name='Downvotes')),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Topics')),
            ],
        ),
    ]
