# Generated by Django 2.2.6 on 2019-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_posts_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='topic_sub',
            new_name='topic_desc',
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_name',
            field=models.CharField(default='School', max_length=255),
            preserve_default=False,
        ),
    ]
