# Generated by Django 2.2.6 on 2019-11-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191031_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
    ]
