# Generated by Django 2.2.6 on 2019-11-09 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20191109_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='timetable',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
