# Generated by Django 2.2.6 on 2019-11-10 07:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191109_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_topics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
