# Generated by Django 2.2.6 on 2019-11-21 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_notes_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
