# Generated by Django 2.2.6 on 2020-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_tasks_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='List Title', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable',
            field=models.TextField(default=''),
        ),
    ]
