# Generated by Django 2.2.6 on 2020-10-11 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20201011_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 11, 3, 46, 540143, tzinfo=utc)),
        ),
    ]
