# Generated by Django 2.2.6 on 2020-10-11 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 11, 5, 4, 394198, tzinfo=utc)),
        ),
    ]
